# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3rqt9LoVQQDnzm1Jnzps7__6nonAe1F
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5])
y=np.array([0,200])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,3,5,7])
y=np.array([4,7,2,8])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([4,9,2,10])
plt.plot(y, marker='o')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([4,9,2,10])
plt.plot(y, marker='o', ms=20)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([2,7,3,10])
plt.plot(y, marker='o', ms=20, mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([1,2,3,4])
y1=np.array([4,9,2,10])
x2=np.array([1,2,3,4])
y2=np.array([7,3,8,12])
plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([4,9,2,12])
plt.plot(y, marker='o', ms=20, mfc='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5])
y=np.array([0,6,12,22,28,36])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([0,6,8,11,13,6])
plt.scatter(x,y,color='red')
x=np.array([12,6,14,15,9,11])
y=np.array([6,8,9,13,11,7])
plt.scatter(x,y,color='green')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([0,4,8,3,12,9])
mycolor=['red','green','purple','lime','aqua','yellow']
plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([0,6,8,11,13,6])
mycolor=['red','green','purple','lime','aqua','yellow']
size=[20,70,120,90,20,180]
plt.scatter(x,y,color=mycolor,s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([4,9,2,12])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([25,35,15,25])
plt.pie(y)
plt.show()